name: Test on push

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Echo branch name - ${{ steps.extract_branch.outputs.branch }}
        run: echo ${{ steps.extract_branch.outputs.branch }}
